# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SEQUOIA
                                 A QGIS plugin
 module SEQUOIA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-06
        copyright            : (C) 2019 by Matthieu CHEVEREAU
        email                : matthieuchevereau@yahoo.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SEQUOIA class from file SEQUOIA.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SEQUOIA import SEQUOIA
    return SEQUOIA(iface)
